"""
Regression tests for the write-operation routing fixes.

These cover the three defects that blocked INSERT:

1. ``crud/deterministic.py``  -- a write request must be recognised
   even when the LLM intent parser abstains.
2. ``crud/columns.py``        -- an integer primary key is generated by
   the database and must never be a required user field.
3. ``_clean_generated_sql``   -- prose must never be turned into SQL by
   the English word "with".

Runnable two ways:

    python backend/tests/test_write_routing.py
    pytest backend/tests
"""

from __future__ import annotations

import sys
from pathlib import Path

# Make ``app`` importable when run directly.
_BACKEND_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_BACKEND_DIR))

# groq_agent builds a client at import time, so the key must be loaded
# before app.agent.orchestrator is imported.
from dotenv import load_dotenv  # noqa: E402

load_dotenv(_BACKEND_DIR / ".env")

from app.crud.columns import (  # noqa: E402
    build_insert_form_fields,
    field_type_for,
    is_auto_generated_column,
    is_required_column,
    required_insert_columns,
)
from app.crud.deterministic import (  # noqa: E402
    build_deterministic_intent,
    detect_write_operation,
)
from app.agent.orchestrator import _clean_generated_sql  # noqa: E402


# -------------------------------------------------------------
# Shared fixtures
# -------------------------------------------------------------

CUSTOMERS_SCHEMA = {
    "customer_id": {
        "type": "INTEGER",
        "nullable": False,
        "primary_key": True,
        "default": None,
    },
    "name": {
        "type": "VARCHAR",
        "nullable": False,
        "primary_key": False,
        "default": None,
    },
    "email": {
        "type": "VARCHAR",
        "nullable": False,
        "primary_key": False,
        "default": None,
    },
    "city": {
        "type": "VARCHAR",
        "nullable": True,
        "primary_key": False,
        "default": None,
    },
}

DEMO_SCHEMA = {
    "customers": CUSTOMERS_SCHEMA,
    "products": {
        "product_id": {
            "type": "INTEGER",
            "nullable": False,
            "primary_key": True,
            "default": None,
        },
        "name": {
            "type": "VARCHAR",
            "nullable": False,
            "primary_key": False,
            "default": None,
        },
        "price": {
            "type": "FLOAT",
            "nullable": True,
            "primary_key": False,
            "default": None,
        },
    },
}


# -------------------------------------------------------------
# 1. Write-operation detection
# -------------------------------------------------------------

def test_create_requests_are_detected():
    for message in (
        "add a new customer",
        "add a customer",
        "create a new product called Laptop",
        "insert a record",
        "register a new user",
    ):
        assert detect_write_operation(message) == "create", message


def test_update_requests_are_detected():
    for message in (
        "update customer 1 city to Salem",
        "change the name of customer 1",
        "modify employee 2 salary",
        "edit product 3 price",
        "rename customer 1",
    ):
        assert detect_write_operation(message) == "update", message


def test_delete_requests_are_detected():
    for message in (
        "delete customer 3",
        "remove customer 3",
        "erase order 9",
        "delet customer 3",
        "delte customer 3",
    ):
        assert detect_write_operation(message) == "delete", message


def test_read_requests_are_not_write_requests():
    for message in (
        "show all customers",
        "list products",
        "count orders",
        "how many customers are there",
        "give me the average price of products",
        "find customer 3",
        "what is in the database",
        "set of customers",
    ):
        assert detect_write_operation(message) is None, message


def test_add_up_is_a_read_idiom_not_a_create():
    # Regression: "add up" contains the create keyword "add" but means
    # SUM(...). It must not be routed to the insert form.
    for message in (
        "add up the total price of products",
        "adds up the totals",
        "adding up all the prices",
        "add the prices together",
    ):
        assert detect_write_operation(message) is None, message


def test_genuine_create_containing_up_is_not_neutralized():
    # The read-idiom rewriting must stay narrow. "up" appearing later
    # in a real create request must not disable write detection.
    assert detect_write_operation(
        "add a product with price up to 100"
    ) == "create"

    assert detect_write_operation(
        "create a customer and follow up later"
    ) == "create"


# -------------------------------------------------------------
# 2. Deterministic intent
# -------------------------------------------------------------

def test_intent_resolves_table_from_live_schema():
    intent = build_deterministic_intent(
        "add a new customer",
        DEMO_SCHEMA,
    )

    assert intent is not None
    assert intent["operation"] == "create"
    assert intent["table"] == "customers"


def test_intent_never_invents_a_table():
    intent = build_deterministic_intent(
        "add a new invoice",
        DEMO_SCHEMA,
    )

    assert intent is not None
    assert intent["operation"] == "create"
    # "invoice" is not in the schema, so no table may be claimed.
    assert intent["table"] is None


def test_intent_is_none_for_reads_and_empty_schema():
    assert build_deterministic_intent(
        "show all customers",
        DEMO_SCHEMA,
    ) is None

    assert build_deterministic_intent(
        "add a new customer",
        {},
    ) is None


# -------------------------------------------------------------
# 3. Column rules
# -------------------------------------------------------------

def test_integer_primary_key_is_auto_generated():
    metadata = CUSTOMERS_SCHEMA["customer_id"]

    assert is_auto_generated_column("customer_id", metadata) is True
    assert is_required_column("customer_id", metadata) is False


def test_non_integer_primary_key_is_still_required():
    # A string/UUID primary key carries real user data.
    metadata = {
        "type": "VARCHAR",
        "nullable": False,
        "primary_key": True,
        "default": None,
    }

    assert is_auto_generated_column("account_id", metadata) is False
    assert is_required_column("account_id", metadata) is True


def test_nullable_columns_are_optional():
    assert is_required_column("name", CUSTOMERS_SCHEMA["name"]) is True
    assert is_required_column("city", CUSTOMERS_SCHEMA["city"]) is False


def test_audit_columns_are_never_asked_for():
    for column in ("created_at", "updated_at", "deleted_at"):
        metadata = {"type": "TIMESTAMP", "nullable": False}
        assert is_auto_generated_column(column, metadata) is True


def test_required_insert_columns_matches_the_form():
    # This is the exact regression: the form and the validation must
    # agree, and neither may demand customer_id.
    assert required_insert_columns(CUSTOMERS_SCHEMA) == ["name", "email"]

    fields = build_insert_form_fields(CUSTOMERS_SCHEMA)
    names = [field["name"] for field in fields]

    assert names == ["name", "email", "city"]
    assert "customer_id" not in names

    required_in_form = [
        field["name"] for field in fields if field["required"]
    ]
    assert required_in_form == required_insert_columns(CUSTOMERS_SCHEMA)


def test_field_types():
    assert field_type_for("email", {"type": "VARCHAR"}) == "email"
    assert field_type_for("price", {"type": "FLOAT"}) == "number"
    assert field_type_for("quantity", {"type": "INTEGER"}) == "number"
    assert field_type_for("is_active", {"type": "BOOLEAN"}) == "boolean"
    assert field_type_for("order_date", {"type": "DATE"}) == "date"
    assert field_type_for("name", {"type": "VARCHAR"}) == "text"


# -------------------------------------------------------------
# 4. SQL cleanup
# -------------------------------------------------------------

def test_prose_is_not_mistaken_for_sql():
    # Regression: this produced the statement "with that." and then
    # the error 'COULD operations are not supported.'
    for prose in (
        "I can help with that.",
        "Could you please provide the details (name, email, city)?",
        "Sure, with that in mind here is what I found.",
        "",
    ):
        assert _clean_generated_sql(prose) == "", prose


def test_real_sql_is_preserved():
    assert _clean_generated_sql("SELECT * FROM customers") == (
        "SELECT * FROM customers"
    )

    assert _clean_generated_sql(
        "```sql\nSELECT * FROM customers;\n```"
    ) == "SELECT * FROM customers"

    assert _clean_generated_sql(
        'SELECT * FROM "customers"'
    ) == 'SELECT * FROM "customers"'


def test_cte_is_still_accepted():
    sql = "WITH recent AS (SELECT 1) SELECT * FROM recent"

    assert _clean_generated_sql(sql) == sql


# -------------------------------------------------------------
# Direct runner
# -------------------------------------------------------------

def _run_all() -> int:
    tests = [
        (name, value)
        for name, value in sorted(globals().items())
        if name.startswith("test_") and callable(value)
    ]

    failures = []

    for name, test in tests:
        try:
            test()
            print(f"PASS  {name}")
        except AssertionError as exc:
            failures.append(name)
            print(f"FAIL  {name}: {exc}")
        except Exception as exc:  # noqa: BLE001
            failures.append(name)
            print(f"ERROR {name}: {type(exc).__name__}: {exc}")

    print(f"\n{len(tests) - len(failures)}/{len(tests)} passed")

    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(_run_all())
